### ISSUE TITLE
setup issues

### ISSUE THREAD

**Issue by ShazamSham** [popdynamics/popdynamics#1]
Hi,

Sorry if this is not the correct way to contact you to ask about how to use the repository , but I'm trying to use your popdynamics code to develop models of TB transmission, but I can't set up the environment: you state that I need to install graphviz, but I can't seem to even find this package (I'm using PyCharm - as recommended by James Trauer from the AutUMN group in Melbourne). Can you please let me know how to do this in PyCharm (sorry - I'm not an experienced python programmer - just learning and trying to use these tools to do disease modelling not programming). 

I also ran your setup.py script and all I got was this:

"usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied

Process finished with exit code 1"

Is this correct?

**Comment by ShazamSham** [comment]
Sorry - another question:
I seem to be able to run basepop.py fine, but as soon as I try to run sir_model.py I get the following issues in the console:
Traceback (most recent call last):
  File "D:/Sync Folder/Modelling/PythonModel/GitHub/popdynamics/examples/sir_model.py", line 266, in <module>
    model.integrate_discrete_time_stochastic()
  File "D:/Sync Folder/Modelling/PythonModel/GitHub/popdynamics/examples\..\basepop.py", line 714, in integrate_discrete_time_stochastic
    self.calculate_diagnostics()
  File "D:/Sync Folder/Modelling/PythonModel/GitHub/popdynamics/examples\..\basepop.py", line 768, in calculate_diagnostics
    self.get_var_soln('population')
  File "D:/Sync Folder/Modelling/PythonModel/GitHub/popdynamics/examples\..\basepop.py", line 797, in get_var_soln
    i_label = self.var_labels.index(label)
AttributeError: 'dict_keys' object has no attribute 'index'

Process finished with exit code 1

**Comment by ShazamSham** [comment]
Also another issue with trying to run basepop.py:
After running it, I get this issue in the PyCharm console:

Traceback (most recent call last):
  File "D:/Sync Folder/Modelling/PythonModel/popdynamics/popdynamics-master/basepop.py", line 10, in <module>
    from past.utils import old_div
ModuleNotFoundError: No module named 'past'

Process finished with exit code 1

**Comment by ShazamSham** [comment]
Sorry for the frequent messages: I have resolved this now. It seems that I needed to install the "future" package from outside of PyCharm by using this command from the windows command prompt:

C:\Program Files\Python37>python -m pip install future --user

Not very intuitive but I got there in the end.

**Comment by ShazamSham** [comment]
I have sorted this issue - now - it appears I needed to install the "future" package in the windows command console (not from within PyCharm) using the following command:

C:\Program Files\Python37>python -m pip install future --user

This has resolved it and your scripts seem to be running - apolgies for the multiple posts...

**Comment by ShazamSham** [comment]
The graphviz flow chart isn't working - I have been able to install graphviz, but unsure how to link the graphviz file to allow the document that is actually created to open...(I have downloaded the graphviz binary - but I'm not sure what I should be doing with it - where should it be saved in the PyCharm IDE?)

This is the message I get in the console:

Running measles SEIR Model for 200 days...
Basemodel.integrate 201 (201, 4)
Error running graphviz: probably not installed on your system
Running flu SEIR Model for 200 days...
Basemodel.integrate 201 (201, 4)
Error running graphviz: probably not installed on your system
Running SEIR Model with demography for 18250 days...
Basemodel.integrate 18251 (18251, 4)
Error running graphviz: probably not installed on your system
Running SEIR Model with partial immunity for 120 days...
Basemodel.integrate 121 (121, 4)

Process finished with exit code 0

**Comment by jtrauer** [comment]
Hi ShazamSham. Great that you are using this, thanks for your interest. I do find that the biggest issue with using user-written packages in Python is trying to get all the dependencies sorted.

Sounds like the only outstanding issue now is the graphviz plotting. I'm not sure where that is currently at and will ask the other developer @boscoh . We were having trouble with it at one point. That code is just to create the flow diagram, so you should still have all the other functionality even if you comment out the call to graphviz - and it looks like the code did complete somehow despite the graphviz error.

**Comment by ShazamSham** [comment]
Hi James - and thanks for your quick reply. I've come back to trying my modelling in Python. I've been able to at least get the SEIR model and SIR models to run which is great thanks. I'll ignore the flow diagram issue for now - so will comment that part out and enjoy the challenge of making variations on the existing framework code
Thanks again.

**Comment by jtrauer** [comment]
That's great. Hope you find it useful.

**Comment by boscoh** [comment]
Hi ShazamSham, you should be able to run everything despite graphviz - the package will throw an error message and continue. The PATH enviornment on Windows needs to be set to point to the graphviz binary. Here's one user's attempt: https://stackoverflow.com/questions/4571067/installing-pygraphviz-on-windows?rq=1
